import type { PurchaseOrder } from './types'

export function generateSamplePurchaseOrders(): PurchaseOrder[] {
  const now = new Date()
  
  const getDateDaysAgo = (days: number) => {
    const date = new Date(now)
    date.setDate(date.getDate() - days)
    return date.toISOString().split('T')[0]
  }

  return [
    {
      id: 'po1',
      poNumber: 'PO-2024-001',
      supplier: 'ssactivewear',
      status: 'received',
      orderDate: getDateDaysAgo(90),
      expectedDeliveryDate: getDateDaysAgo(85),
      actualDeliveryDate: getDateDaysAgo(84),
      lineItems: [
        {
          id: 'poli1',
          supplier: 'ssactivewear',
          styleId: 'G500',
          styleName: 'Heavy Cotton™ T-Shirt',
          brandName: 'Gildan',
          colorName: 'Black',
          colorCode: 'BLK',
          sizes: { XS: 5, S: 10, M: 15, L: 20, XL: 15, '2XL': 5, '3XL': 0 },
          quantityOrdered: 70,
          quantityReceived: 70,
          unitCost: 3.50,
          lineTotal: 245.00,
          associatedOrders: [],
          receivedItems: [{
            id: 'ri1',
            sizes: { XS: 5, S: 10, M: 15, L: 20, XL: 15, '2XL': 5, '3XL': 0 },
            receivedDate: getDateDaysAgo(84),
            receivedBy: 'John Doe',
          }],
        },
      ],
      subtotal: 245.00,
      shipping: 15.00,
      total: 260.00,
      accuracyRating: 100,
      deliveryRating: 5,
      createdAt: getDateDaysAgo(90),
      updatedAt: getDateDaysAgo(84),
    },
    {
      id: 'po2',
      poNumber: 'PO-2024-002',
      supplier: 'sanmar',
      status: 'received',
      orderDate: getDateDaysAgo(75),
      expectedDeliveryDate: getDateDaysAgo(70),
      actualDeliveryDate: getDateDaysAgo(69),
      lineItems: [
        {
          id: 'poli2',
          supplier: 'sanmar',
          styleId: 'PC54',
          styleName: 'Core Cotton Tee',
          brandName: 'Port & Company',
          colorName: 'Navy',
          colorCode: 'NVY',
          sizes: { XS: 0, S: 12, M: 18, L: 24, XL: 12, '2XL': 6, '3XL': 3 },
          quantityOrdered: 75,
          quantityReceived: 75,
          unitCost: 3.25,
          lineTotal: 243.75,
          associatedOrders: [],
          receivedItems: [{
            id: 'ri2',
            sizes: { XS: 0, S: 12, M: 18, L: 24, XL: 12, '2XL': 6, '3XL': 3 },
            receivedDate: getDateDaysAgo(69),
            receivedBy: 'Jane Smith',
          }],
        },
      ],
      subtotal: 243.75,
      shipping: 12.50,
      total: 256.25,
      accuracyRating: 95,
      deliveryRating: 4,
      qualityIssues: ['One shirt had minor thread issue'],
      createdAt: getDateDaysAgo(75),
      updatedAt: getDateDaysAgo(69),
    },
    {
      id: 'po3',
      poNumber: 'PO-2024-003',
      supplier: 'ssactivewear',
      status: 'received',
      orderDate: getDateDaysAgo(60),
      expectedDeliveryDate: getDateDaysAgo(55),
      actualDeliveryDate: getDateDaysAgo(53),
      lineItems: [
        {
          id: 'poli3',
          supplier: 'ssactivewear',
          styleId: '18500',
          styleName: 'Heavy Blend™ Hooded Sweatshirt',
          brandName: 'Gildan',
          colorName: 'Charcoal',
          colorCode: 'CHAR',
          sizes: { XS: 2, S: 8, M: 12, L: 18, XL: 10, '2XL': 5, '3XL': 0 },
          quantityOrdered: 55,
          quantityReceived: 55,
          unitCost: 12.50,
          lineTotal: 687.50,
          associatedOrders: [],
          receivedItems: [{
            id: 'ri3',
            sizes: { XS: 2, S: 8, M: 12, L: 18, XL: 10, '2XL': 5, '3XL': 0 },
            receivedDate: getDateDaysAgo(53),
            receivedBy: 'John Doe',
          }],
        },
      ],
      subtotal: 687.50,
      shipping: 20.00,
      total: 707.50,
      accuracyRating: 100,
      deliveryRating: 5,
      createdAt: getDateDaysAgo(60),
      updatedAt: getDateDaysAgo(53),
    },
    {
      id: 'po4',
      poNumber: 'PO-2024-004',
      supplier: 'ssactivewear',
      status: 'received',
      orderDate: getDateDaysAgo(45),
      expectedDeliveryDate: getDateDaysAgo(40),
      actualDeliveryDate: getDateDaysAgo(42),
      lineItems: [
        {
          id: 'poli4',
          supplier: 'ssactivewear',
          styleId: 'G200',
          styleName: 'Ultra Cotton® T-Shirt',
          brandName: 'Gildan',
          colorName: 'White',
          colorCode: 'WHT',
          sizes: { XS: 10, S: 20, M: 30, L: 40, XL: 25, '2XL': 10, '3XL': 5 },
          quantityOrdered: 140,
          quantityReceived: 140,
          unitCost: 3.75,
          lineTotal: 525.00,
          associatedOrders: [],
          receivedItems: [{
            id: 'ri4',
            sizes: { XS: 10, S: 20, M: 30, L: 40, XL: 25, '2XL': 10, '3XL': 5 },
            receivedDate: getDateDaysAgo(42),
            receivedBy: 'Mike Johnson',
          }],
        },
      ],
      subtotal: 525.00,
      shipping: 18.00,
      total: 543.00,
      accuracyRating: 90,
      deliveryRating: 3,
      qualityIssues: ['Delivery was 2 days late', 'Wrong size labels on 3 items'],
      createdAt: getDateDaysAgo(45),
      updatedAt: getDateDaysAgo(42),
    },
    {
      id: 'po5',
      poNumber: 'PO-2024-005',
      supplier: 'sanmar',
      status: 'received',
      orderDate: getDateDaysAgo(30),
      expectedDeliveryDate: getDateDaysAgo(25),
      actualDeliveryDate: getDateDaysAgo(24),
      lineItems: [
        {
          id: 'poli5',
          supplier: 'sanmar',
          styleId: 'DT6000',
          styleName: 'District Very Important Tee®',
          brandName: 'District',
          colorName: 'Heather Navy',
          colorCode: 'HNVY',
          sizes: { XS: 5, S: 15, M: 20, L: 25, XL: 15, '2XL': 8, '3XL': 2 },
          quantityOrdered: 90,
          quantityReceived: 90,
          unitCost: 4.25,
          lineTotal: 382.50,
          associatedOrders: [],
          receivedItems: [{
            id: 'ri5',
            sizes: { XS: 5, S: 15, M: 20, L: 25, XL: 15, '2XL': 8, '3XL': 2 },
            receivedDate: getDateDaysAgo(24),
            receivedBy: 'Sarah Williams',
          }],
        },
      ],
      subtotal: 382.50,
      shipping: 14.00,
      total: 396.50,
      accuracyRating: 100,
      deliveryRating: 5,
      createdAt: getDateDaysAgo(30),
      updatedAt: getDateDaysAgo(24),
    },
    {
      id: 'po6',
      poNumber: 'PO-2024-006',
      supplier: 'ssactivewear',
      status: 'received',
      orderDate: getDateDaysAgo(20),
      expectedDeliveryDate: getDateDaysAgo(15),
      actualDeliveryDate: getDateDaysAgo(14),
      lineItems: [
        {
          id: 'poli6',
          supplier: 'ssactivewear',
          styleId: 'G180',
          styleName: 'Adult Heavy Blend™ 8 oz. 50/50 Hood',
          brandName: 'Gildan',
          colorName: 'Sport Grey',
          colorCode: 'SPGRY',
          sizes: { XS: 3, S: 10, M: 15, L: 20, XL: 12, '2XL': 6, '3XL': 4 },
          quantityOrdered: 70,
          quantityReceived: 70,
          unitCost: 11.00,
          lineTotal: 770.00,
          associatedOrders: [],
          receivedItems: [{
            id: 'ri6',
            sizes: { XS: 3, S: 10, M: 15, L: 20, XL: 12, '2XL': 6, '3XL': 4 },
            receivedDate: getDateDaysAgo(14),
            receivedBy: 'John Doe',
          }],
        },
      ],
      subtotal: 770.00,
      shipping: 22.00,
      total: 792.00,
      accuracyRating: 98,
      deliveryRating: 5,
      qualityIssues: ['Minor packaging damage on box 2'],
      createdAt: getDateDaysAgo(20),
      updatedAt: getDateDaysAgo(14),
    },
    {
      id: 'po7',
      poNumber: 'PO-2024-007',
      supplier: 'sanmar',
      status: 'received',
      orderDate: getDateDaysAgo(12),
      expectedDeliveryDate: getDateDaysAgo(7),
      actualDeliveryDate: getDateDaysAgo(6),
      lineItems: [
        {
          id: 'poli7',
          supplier: 'sanmar',
          styleId: 'PC61',
          styleName: 'Essential Tee',
          brandName: 'Port & Company',
          colorName: 'Kelly Green',
          colorCode: 'KGRN',
          sizes: { XS: 4, S: 12, M: 18, L: 22, XL: 14, '2XL': 6, '3XL': 4 },
          quantityOrdered: 80,
          quantityReceived: 80,
          unitCost: 3.00,
          lineTotal: 240.00,
          associatedOrders: [],
          receivedItems: [{
            id: 'ri7',
            sizes: { XS: 4, S: 12, M: 18, L: 22, XL: 14, '2XL': 6, '3XL': 4 },
            receivedDate: getDateDaysAgo(6),
            receivedBy: 'Jane Smith',
          }],
        },
      ],
      subtotal: 240.00,
      shipping: 11.00,
      total: 251.00,
      accuracyRating: 100,
      deliveryRating: 5,
      createdAt: getDateDaysAgo(12),
      updatedAt: getDateDaysAgo(6),
    },
    {
      id: 'po8',
      poNumber: 'PO-2024-008',
      supplier: 'ssactivewear',
      status: 'ordered',
      orderDate: getDateDaysAgo(5),
      expectedDeliveryDate: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      lineItems: [
        {
          id: 'poli8',
          supplier: 'ssactivewear',
          styleId: 'G640',
          styleName: 'Softstyle® T-Shirt',
          brandName: 'Gildan',
          colorName: 'Red',
          colorCode: 'RED',
          sizes: { XS: 6, S: 14, M: 20, L: 28, XL: 18, '2XL': 8, '3XL': 6 },
          quantityOrdered: 100,
          quantityReceived: 0,
          unitCost: 3.25,
          lineTotal: 325.00,
          associatedOrders: [],
        },
      ],
      subtotal: 325.00,
      shipping: 15.00,
      total: 340.00,
      createdAt: getDateDaysAgo(5),
      updatedAt: getDateDaysAgo(5),
    },
  ]
}
